
export const emojis = [
  // Smileys & Emotion (Face Smiling)
  { emoji: '😀', name: 'grinning face', tags: ['smile', 'happy', 'grin'] },
  { emoji: '😃', name: 'grinning face with big eyes', tags: ['smile', 'happy', 'excited'] },
  { emoji: '😄', name: 'grinning face with smiling eyes', tags: ['smile', 'happy', 'joy'] },
  { emoji: '😁', name: 'beaming face with smiling eyes', tags: ['smile', 'happy', 'beam'] },
  { emoji: '😆', name: 'grinning squinting face', tags: ['happy', 'joy', 'laugh'] },
  { emoji: '😅', name: 'grinning face with sweat', tags: ['happy', 'nervous', 'relief'] },
  { emoji: '🤣', name: 'rolling on the floor laughing', tags: ['lol', 'laugh', 'rofl'] },
  { emoji: '😂', name: 'face with tears of joy', tags: ['joy', 'laugh', 'cry'] },
  { emoji: '🙂', name: 'slightly smiling face', tags: ['smile', 'gentle', 'happy'] },
  { emoji: '🙃', name: 'upside-down face', tags: ['silly', 'joke', 'fool'] },
  { emoji: '😉', name: 'winking face', tags: ['wink', 'flirt', 'joke'] },
  { emoji: '😊', name: 'smiling face with smiling eyes', tags: ['smile', 'happy', 'blush'] },
  { emoji: '😇', name: 'smiling face with halo', tags: ['angel', 'innocent', 'good'] },
  { emoji: '🥰', name: 'smiling face with hearts', tags: ['love', 'crush', 'adore'] },
  { emoji: '😍', name: 'smiling face with heart-eyes', tags: ['love', 'crush', 'heart'] },
  { emoji: '🤩', name: 'star-struck', tags: ['wow', 'amazed', 'stars'] },
  { emoji: '😘', name: 'face blowing a kiss', tags: ['kiss', 'love', 'flirt'] },
  { emoji: '😗', name: 'kissing face', tags: ['kiss', 'love', 'romance'] },
  { emoji: '😙', name: 'kissing face with smiling eyes', tags: ['kiss', 'love', 'happy'] },
  { emoji: '😚', name: 'kissing face with closed eyes', tags: ['kiss', 'love', 'romance'] },
  { emoji: '😋', name: 'face savoring food', tags: ['yum', 'food', 'tasty'] },
  { emoji: '😛', name: 'face with tongue', tags: ['silly', 'playful', 'joke'] },
  { emoji: '😜', name: 'winking face with tongue', tags: ['silly', 'joke', 'fun'] },
  { emoji: '🤪', name: 'zany face', tags: ['crazy', 'wild', 'goofy'] },
  { emoji: '😝', name: 'squinting face with tongue', tags: ['silly', 'yuck', 'playful'] },
  { emoji: '🤑', name: 'money-mouth face', tags: ['money', 'rich', 'greed'] },
  { emoji: '🤗', name: 'hugging face', tags: ['hug', 'love', 'warm'] },
  { emoji: '🤭', name: 'face with hand over mouth', tags: ['oops', 'secret', 'shh'] },
  { emoji: '🤫', name: 'shushing face', tags: ['quiet', 'shh', 'secret'] },
  { emoji: '🤔', name: 'thinking face', tags: ['think', 'ponder', 'hmm'] },
  { emoji: '🤐', name: 'zipper-mouth face', tags: ['quiet', 'secret', 'zip'] },
  { emoji: '🤨', name: 'face with raised eyebrow', tags: ['skeptical', 'doubt', 'hmm'] },
  { emoji: '😐', name: 'neutral face', tags: ['meh', 'ok', 'neutral'] },
  { emoji: '😑', name: 'expressionless face', tags: ['blank', 'deadpan', 'meh'] },
  { emoji: '😶', name: 'face without mouth', tags: ['silent', 'speechless', 'mute'] },
  { emoji: '😏', name: 'smirking face', tags: ['smug', 'flirt', 'sly'] },
  { emoji: '😒', name: 'unamused face', tags: ['bored', 'annoyed', 'unamused'] },
  { emoji: '🙄', name: 'face with rolling eyes', tags: ['annoyed', 'sarcasm', 'eye roll'] },
  { emoji: '😬', name: 'grimacing face', tags: ['awkward', 'cringe', 'nervous'] },
  { emoji: '🤥', name: 'lying face', tags: ['lie', 'fake', 'pinocchio'] },
  { emoji: '😌', name: 'relieved face', tags: ['relief', 'calm', 'peace'] },
  { emoji: '😔', name: 'pensive face', tags: ['sad', 'disappointed', 'sorry'] },
  { emoji: '😪', name: 'sleepy face', tags: ['sleep', 'tired', 'yawn'] },
  { emoji: '🤤', name: 'drooling face', tags: ['hungry', 'food', 'desire'] },
  { emoji: '😴', name: 'sleeping face', tags: ['sleep', 'tired', 'zzz'] },
  { emoji: '😷', name: 'face with medical mask', tags: ['sick', 'health', 'covid'] },
  { emoji: '🤒', name: 'face with thermometer', tags: ['sick', 'fever', 'ill'] },
  { emoji: '🤕', name: 'face with head-bandage', tags: ['hurt', 'injury', 'pain'] },
  { emoji: '🤢', name: 'nauseated face', tags: ['sick', 'gross', 'nausea'] },
  { emoji: '🤮', name: 'face vomiting', tags: ['sick', 'puke', 'gross'] },
  { emoji: '🤧', name: 'sneezing face', tags: ['sick', 'cold', 'achoo'] },
  { emoji: '🥵', name: 'hot face', tags: ['hot', 'sweat', 'summer'] },
  { emoji: '🥶', name: 'cold face', tags: ['cold', 'freeze', 'winter'] },
  { emoji: '🥴', name: 'woozy face', tags: ['drunk', 'dizzy', 'tipsy'] },
  { emoji: '😵', name: 'knocked-out face', tags: ['shock', 'wow', 'dead'] },
  { emoji: '🤯', name: 'exploding head', tags: ['mind blown', 'shock', 'wow'] },
  { emoji: '🤠', name: 'cowboy hat face', tags: ['cowboy', 'western', 'yeehaw'] },
  { emoji: '🥳', name: 'partying face', tags: ['party', 'celebrate', 'fun'] },
  { emoji: '😎', name: 'smiling face with sunglasses', tags: ['cool', 'chill', 'awesome'] },
  { emoji: '🤓', name: 'nerd face', tags: ['geek', 'smart', 'glasses'] },
  { emoji: '🧐', name: 'face with monocle', tags: ['fancy', 'examining', 'study'] },
  { emoji: '😕', name: 'confused face', tags: ['confused', 'huh', 'what'] },
  { emoji: '😟', name: 'worried face', tags: ['worried', 'anxious', 'concern'] },
  { emoji: '🙁', name: 'slightly frowning face', tags: ['sad', 'disappointed', 'frown'] },
  { emoji: '☹️', name: 'frowning face', tags: ['sad', 'upset', 'frown'] },
  { emoji: '😮', name: 'face with open mouth', tags: ['surprise', 'wow', 'shock'] },
  { emoji: '😯', name: 'hushed face', tags: ['surprise', 'quiet', 'wow'] },
  { emoji: '😲', name: 'astonished face', tags: ['shock', 'wow', 'amaze'] },
  { emoji: '😳', name: 'flushed face', tags: ['embarrassed', 'blush', 'shy'] },
  { emoji: '🥺', name: 'pleading face', tags: ['puppy eyes', 'please', 'beg'] },
  { emoji: '😢', name: 'crying face', tags: ['sad', 'tear', 'cry'] },
  { emoji: '😭', name: 'loudly crying face', tags: ['cry', 'sad', 'tears'] },
  { emoji: '😤', name: 'face with steam from nose', tags: ['frustrated', 'angry', 'annoyed'] },
  { emoji: '😡', name: 'pouting face', tags: ['angry', 'mad', 'pout'] },
  { emoji: '😠', name: 'angry face', tags: ['angry', 'mad', 'grrr'] },
  { emoji: '🤬', name: 'face with symbols on mouth', tags: ['swear', 'cursing', 'angry'] },
  { emoji: '😈', name: 'smiling face with horns', tags: ['devil', 'mischief', 'evil'] },
  { emoji: '👿', name: 'angry face with horns', tags: ['devil', 'angry', 'demon'] },
  { emoji: '💀', name: 'skull', tags: ['death', 'danger', 'spooky'] },
  { emoji: '☠️', name: 'skull and crossbones', tags: ['danger', 'pirate', 'death'] },
  { emoji: '💩', name: 'pile of poo', tags: ['poop', 'crap', 'funny'] },
  { emoji: '🤡', name: 'clown face', tags: ['clown', 'circus', 'funny'] },
  { emoji: '👹', name: 'ogre', tags: ['monster', 'demon', 'oni'] },
  { emoji: '👺', name: 'goblin', tags: ['monster', 'demon', 'tengu'] },
  { emoji: '👻', name: 'ghost', tags: ['spooky', 'halloween', 'boo'] },
  { emoji: '👽', name: 'alien', tags: ['ufo', 'space', 'extraterrestrial'] },
  { emoji: '👾', name: 'alien monster', tags: ['game', 'retro', 'space'] },
  { emoji: '🤖', name: 'robot', tags: ['robot', 'ai', 'tech'] },

  // People & Body (Hands)
  { emoji: '👍', name: 'thumbs up', tags: ['yes', 'good', 'approve'] },
  { emoji: '👎', name: 'thumbs down', tags: ['no', 'bad', 'disapprove'] },
  { emoji: '👏', name: 'clapping hands', tags: ['applause', 'bravo', 'congrats'] },
  { emoji: '🙌', name: 'raising hands', tags: ['celebrate', 'hooray', 'praise'] },
  { emoji: '👐', name: 'open hands', tags: ['hug', 'open', 'welcome'] },
  { emoji: '🤲', name: 'palms up together', tags: ['pray', 'hold', 'offer'] },
  { emoji: '🤝', name: 'handshake', tags: ['deal', 'agree', 'meeting'] },
  { emoji: '🙏', name: 'folded hands', tags: ['please', 'pray', 'thanks'] },
  { emoji: '✌️', name: 'victory hand', tags: ['peace', 'v', 'hippie'] },
  { emoji: '🤞', name: 'crossed fingers', tags: ['luck', 'hope', 'wish'] },
  { emoji: '🤟', name: 'love-you gesture', tags: ['love', 'rock', 'sign'] },
  { emoji: '🤘', name: 'sign of the horns', tags: ['rock', 'metal', 'music'] },
  { emoji: '🤙', name: 'call me hand', tags: ['call', 'shaka', 'surf'] },
  { emoji: '👈', name: 'backhand index pointing left', tags: ['left', 'point', 'direction'] },
  { emoji: '👉', name: 'backhand index pointing right', tags: ['right', 'point', 'direction'] },
  { emoji: '👆', name: 'backhand index pointing up', tags: ['up', 'point', 'direction'] },
  { emoji: '👇', name: 'backhand index pointing down', tags: ['down', 'point', 'direction'] },
  { emoji: '☝️', name: 'index pointing up', tags: ['up', 'point', 'one'] },
  { emoji: '✋', name: 'raised hand', tags: ['stop', 'high five', 'hand'] },
  { emoji: '🤚', name: 'raised back of hand', tags: ['stop', 'halt', 'hand'] },
  { emoji: '🖐️', name: 'hand with fingers splayed', tags: ['hand', 'five', 'open'] },
  { emoji: '🖖', name: 'vulcan salute', tags: ['spock', 'star trek', 'scifi'] },
  { emoji: '👋', name: 'waving hand', tags: ['hello', 'goodbye', 'hi'] },
  { emoji: '💪', name: 'flexed biceps', tags: ['strong', 'muscle', 'power'] },
  { emoji: '🦾', name: 'mechanical arm', tags: ['cyborg', 'prosthetic', 'tech'] },
  { emoji: '🖕', name: 'middle finger', tags: ['angry', 'rude', 'flip'] },
  { emoji: '✍️', name: 'writing hand', tags: ['write', 'pen', 'note'] },
  { emoji: '🙋', name: 'raising hand', tags: ['question', 'volunteer', 'me'] },
  { emoji: '🙆', name: 'gesture OK', tags: ['ok', 'yes', 'agree'] },
  { emoji: '🙅', name: 'gesture NO', tags: ['no', 'nope', 'decline'] },
  { emoji: '🙇', name: 'person bowing', tags: ['sorry', 'apology', 'bow'] },
  { emoji: '🤷', name: 'person shrugging', tags: ['whatever', 'idk', 'meh'] },
  { emoji: '💁', name: 'person tipping hand', tags: ['sassy', 'info', 'attitude'] },
  { emoji: '🙎', name: 'person pouting', tags: ['upset', 'sad', 'moody'] },
  { emoji: '🙍', name: 'person frowning', tags: ['sad', 'upset', 'disappointed'] },

  // Hearts
  { emoji: '❤️', name: 'red heart', tags: ['love', 'heart', 'passion'] },
  { emoji: '🧡', name: 'orange heart', tags: ['heart', 'warm', 'fall'] },
  { emoji: '💛', name: 'yellow heart', tags: ['heart', 'friendship', 'sun'] },
  { emoji: '💚', name: 'green heart', tags: ['heart', 'nature', 'eco'] },
  { emoji: '💙', name: 'blue heart', tags: ['heart', 'trust', 'ocean'] },
  { emoji: '💜', name: 'purple heart', tags: ['heart', 'royalty', 'spirit'] },
  { emoji: '🖤', name: 'black heart', tags: ['heart', 'dark', 'goth'] },
  { emoji: '🤍', name: 'white heart', tags: ['heart', 'pure', 'clean'] },
  { emoji: '🤎', name: 'brown heart', tags: ['heart', 'earth', 'warm'] },
  { emoji: '💔', name: 'broken heart', tags: ['heartbreak', 'sad', 'pain'] },
  { emoji: '💕', name: 'two hearts', tags: ['love', 'couple', 'romance'] },
  { emoji: '💞', name: 'revolving hearts', tags: ['love', 'spin', 'romance'] },
  { emoji: '💓', name: 'beating heart', tags: ['love', 'alive', 'throb'] },
  { emoji: '💗', name: 'growing heart', tags: ['love', 'grow', 'excited'] },
  { emoji: '💖', name: 'sparkling heart', tags: ['love', 'sparkle', 'adore'] },
  { emoji: '💘', name: 'heart with arrow', tags: ['cupid', 'love', 'arrow'] },
  { emoji: '💝', name: 'heart with ribbon', tags: ['gift', 'love', 'valentine'] },

  // Objects
  { emoji: '💯', name: 'hundred points', tags: ['100', 'perfect', 'score'] },
  { emoji: '🔥', name: 'fire', tags: ['hot', 'lit', 'cool'] },
  { emoji: '⭐', name: 'star', tags: ['favorite', 'rate', 'excellent'] },
  { emoji: '🌟', name: 'glowing star', tags: ['shine', 'sparkle', 'bright'] },
  { emoji: '✨', name: 'sparkles', tags: ['magic', 'shiny', 'new'] },
  { emoji: '💫', name: 'dizzy', tags: ['spin', 'magic', 'comet'] },
  { emoji: '🎉', name: 'party popper', tags: ['celebrate', 'party', 'congrats'] },
  { emoji: '🎊', name: 'confetti ball', tags: ['celebrate', 'party', 'woo'] },
  { emoji: '🎈', name: 'balloon', tags: ['party', 'birthday', 'celebrate'] },
  { emoji: '🎁', name: 'wrapped gift', tags: ['present', 'birthday', 'surprise'] },
  { emoji: '🎂', name: 'birthday cake', tags: ['birthday', 'cake', 'celebrate'] },
  { emoji: '🍰', name: 'shortcake', tags: ['cake', 'dessert', 'sweet'] },
  { emoji: '☕', name: 'hot beverage', tags: ['coffee', 'cafe', 'morning'] },
  { emoji: '🍵', name: 'teacup without handle', tags: ['tea', 'green', 'calm'] },
  { emoji: '🍺', name: 'beer mug', tags: ['beer', 'drink', 'alcohol'] },
  { emoji: '🍻', name: 'clinking beer mugs', tags: ['cheers', 'toast', 'party'] },
  { emoji: '🥂', name: 'clinking glasses', tags: ['cheers', 'toast', 'celebrate'] },
  { emoji: '🍷', name: 'wine glass', tags: ['wine', 'fancy', 'dinner'] },
  { emoji: '🍸', name: 'cocktail glass', tags: ['drink', 'party', 'fancy'] },
  { emoji: '🍕', name: 'pizza', tags: ['food', 'italian', 'cheese'] },
  { emoji: '🍔', name: 'hamburger', tags: ['burger', 'food', 'fast food'] },
  { emoji: '🌮', name: 'taco', tags: ['food', 'mexican', 'yum'] },
  { emoji: '🍩', name: 'doughnut', tags: ['food', 'sweet', 'dessert'] },
  { emoji: '🍪', name: 'cookie', tags: ['food', 'sweet', 'snack'] },
  { emoji: '🎵', name: 'musical note', tags: ['music', 'song', 'melody'] },
  { emoji: '🎶', name: 'musical notes', tags: ['music', 'sing', 'melody'] },
  { emoji: '🎤', name: 'microphone', tags: ['sing', 'karaoke', 'mic'] },
  { emoji: '🎧', name: 'headphone', tags: ['music', 'listen', 'audio'] },
  { emoji: '📚', name: 'books', tags: ['read', 'study', 'library'] },
  { emoji: '📝', name: 'memo', tags: ['write', 'note', 'todo'] },
  { emoji: '✏️', name: 'pencil', tags: ['write', 'draw', 'edit'] },
  { emoji: '🖊️', name: 'pen', tags: ['write', 'sign', 'ink'] },
  { emoji: '💡', name: 'light bulb', tags: ['idea', 'think', 'inspiration'] },
  { emoji: '🔑', name: 'key', tags: ['unlock', 'access', 'password'] },
  { emoji: '🔒', name: 'locked', tags: ['secure', 'private', 'lock'] },
  { emoji: '🔓', name: 'unlocked', tags: ['open', 'public', 'unlock'] },
  { emoji: '⚡', name: 'high voltage', tags: ['fast', 'energy', 'power'] },
  { emoji: '💧', name: 'droplet', tags: ['water', 'drop', 'tear'] },
  { emoji: '🌈', name: 'rainbow', tags: ['pride', 'color', 'gay'] },
  { emoji: '☀️', name: 'sun', tags: ['sunny', 'day', 'bright'] },
  { emoji: '🌙', name: 'crescent moon', tags: ['night', 'sleep', 'dark'] },
  { emoji: '🌊', name: 'water wave', tags: ['ocean', 'sea', 'surf'] },
  { emoji: '❄️', name: 'snowflake', tags: ['winter', 'cold', 'ice'] },
  { emoji: '⛄', name: 'snowman without snow', tags: ['winter', 'snow', 'cold'] },
  { emoji: '🚀', name: 'rocket', tags: ['space', 'launch', 'fast'] },
  { emoji: '✈️', name: 'airplane', tags: ['fly', 'travel', 'flight'] },
  { emoji: '🚗', name: 'automobile', tags: ['car', 'drive', 'vehicle'] },
  { emoji: '🏠', name: 'house', tags: ['home', 'building', 'living'] },
  { emoji: '🏢', name: 'office building', tags: ['work', 'company', 'corporate'] },
  { emoji: '💻', name: 'laptop', tags: ['computer', 'work', 'code'] },
  { emoji: '🖥️', name: 'desktop computer', tags: ['computer', 'work', 'screen'] },
  { emoji: '⌨️', name: 'keyboard', tags: ['type', 'input', 'keys'] },
  { emoji: '🖱️', name: 'computer mouse', tags: ['computer', 'click', 'gaming'] },
  { emoji: '📱', name: 'mobile phone', tags: ['phone', 'mobile', 'cell'] },

  // Symbols
  { emoji: '✅', name: 'check mark button', tags: ['done', 'complete', 'ok'] },
  { emoji: '❌', name: 'cross mark', tags: ['no', 'wrong', 'cancel'] },
  { emoji: '⚠️', name: 'warning', tags: ['alert', 'danger', 'caution'] },
  { emoji: '🚫', name: 'prohibited', tags: ['no', 'block', 'denied'] },
  { emoji: '➕', name: 'plus', tags: ['add', 'more', 'increase'] },
  { emoji: '➖', name: 'minus', tags: ['remove', 'less', 'decrease'] },
  { emoji: '❓', name: 'question mark', tags: ['what', 'huh', 'ask'] },
  { emoji: '❗', name: 'exclamation mark', tags: ['important', 'wow', 'alert'] },
  { emoji: '💬', name: 'speech balloon', tags: ['chat', 'talk', 'message'] },
  { emoji: '💭', name: 'thought balloon', tags: ['think', 'dream', 'imagine'] },
  { emoji: '👁️', name: 'eye', tags: ['see', 'look', 'watch'] },
  { emoji: '🧠', name: 'brain', tags: ['smart', 'think', 'mind'] },
  { emoji: '🗑️', name: 'wastebasket', tags: ['delete', 'trash', 'bin'] },
  { emoji: '📌', name: 'pushpin', tags: ['pin', 'mark', 'save'] },
  { emoji: '📎', name: 'paperclip', tags: ['attach', 'file', 'clip'] },
  { emoji: '🔗', name: 'link', tags: ['url', 'chain', 'connect'] },
  { emoji: '📁', name: 'file folder', tags: ['directory', 'file', 'organize'] },
  { emoji: '📂', name: 'open file folder', tags: ['directory', 'files', 'open'] },
  { emoji: '🗂️', name: 'card index dividers', tags: ['organize', 'files', 'sort'] },
  { emoji: '📊', name: 'bar chart', tags: ['stats', 'data', 'analytics'] },
  { emoji: '📈', name: 'chart increasing', tags: ['growth', 'profit', 'increase'] },
  { emoji: '📉', name: 'chart decreasing', tags: ['loss', 'decrease', 'drop'] },
  { emoji: '💾', name: 'floppy disk', tags: ['save', 'disk', 'storage'] },

   // Database & Storage
  { emoji: '💾', name: 'floppy disk', tags: ['save', 'disk', 'storage'] },
  { emoji: '💿', name: 'optical disk', tags: ['cd', 'dvd', 'storage'] },
  { emoji: '📀', name: 'dvd', tags: ['disk', 'movie', 'storage'] },
  { emoji: '🖥️', name: 'desktop computer', tags: ['computer', 'pc', 'work'] },
  { emoji: '💻', name: 'laptop', tags: ['computer', 'work', 'code'] },
  { emoji: '⌨️', name: 'keyboard', tags: ['type', 'input', 'keys'] },
  { emoji: '🖱️', name: 'computer mouse', tags: ['click', 'gaming', 'input'] },
  { emoji: '🖨️', name: 'printer', tags: ['print', 'document', 'office'] },
  { emoji: '⌨️', name: 'keyboard', tags: ['type', 'input', 'keys'] },
  { emoji: '🖥️', name: 'desktop computer', tags: ['computer', 'pc', 'work'] },
  
  // Server & Networking
  { emoji: '🌐', name: 'globe with meridians', tags: ['internet', 'web', 'world'] },
  { emoji: '🔗', name: 'link', tags: ['url', 'chain', 'connect'] },
  { emoji: '📡', name: 'satellite antenna', tags: ['signal', 'broadcast', 'space'] },
  { emoji: '📶', name: 'antenna bars', tags: ['wifi', 'signal', 'network'] },
  { emoji: '📱', name: 'mobile phone', tags: ['phone', 'mobile', 'cell'] },
  { emoji: '📲', name: 'mobile phone with arrow', tags: ['phone', 'incoming', 'call'] },
  { emoji: '☎️', name: 'telephone', tags: ['phone', 'call', 'landline'] },
  { emoji: '📞', name: 'telephone receiver', tags: ['phone', 'call', 'incoming'] },
  { emoji: '📟', name: 'pager', tags: ['old', 'retro', 'device'] },
  { emoji: '📠', name: 'fax machine', tags: ['fax', 'office', 'old'] },
  
  // Cloud & Data
  { emoji: '☁️', name: 'cloud', tags: ['cloud', 'weather', 'storage'] },
  { emoji: '⛅', name: 'sun behind cloud', tags: ['weather', 'cloud', 'day'] },
  { emoji: '🌧️', name: 'cloud with rain', tags: ['weather', 'rain', 'cloud'] },
  { emoji: '🌩️', name: 'cloud with lightning', tags: ['weather', 'storm', 'cloud'] },
  { emoji: '❄️', name: 'snowflake', tags: ['winter', 'cold', 'ice'] },
  
  // Files & Documents
  { emoji: '📁', name: 'file folder', tags: ['folder', 'directory', 'organize'] },
  { emoji: '📂', name: 'open file folder', tags: ['folder', 'open', 'directory'] },
  { emoji: '🗂️', name: 'card index dividers', tags: ['organize', 'files', 'sort'] },
  { emoji: '📇', name: 'card index', tags: ['contacts', 'address', 'organize'] },
  { emoji: '📋', name: 'clipboard', tags: ['copy', 'paste', 'list'] },
  { emoji: '📌', name: 'pushpin', tags: ['pin', 'mark', 'save'] },
  { emoji: '📍', name: 'round pushpin', tags: ['pin', 'location', 'mark'] },
  { emoji: '📎', name: 'paperclip', tags: ['attach', 'file', 'clip'] },
  { emoji: '🖇️', name: 'linked paperclips', tags: ['attach', 'files', 'link'] },
  { emoji: '📏', name: 'straight ruler', tags: ['measure', 'length', 'tools'] },
  { emoji: '📐', name: 'triangular ruler', tags: ['measure', 'geometry', 'tools'] },
  
  // Code & Development
  { emoji: '🔧', name: 'wrench', tags: ['fix', 'tool', 'repair'] },
  { emoji: '🔨', name: 'hammer', tags: ['build', 'tool', 'construct'] },
  { emoji: '⚒️', name: 'hammer and pick', tags: ['build', 'tools', 'construct'] },
  { emoji: '🛠️', name: 'hammer and wrench', tags: ['tools', 'repair', 'build'] },
  { emoji: '⛏️', name: 'pick', tags: ['dig', 'mine', 'tool'] },
  { emoji: '🔩', name: 'nut and bolt', tags: ['fix', 'tool', 'hardware'] },
  { emoji: '⚙️', name: 'gear', tags: ['settings', 'mechanism', 'cog'] },
  { emoji: '🧰', name: 'toolbox', tags: ['tools', 'fix', 'repair'] },
  { emoji: '🧲', name: 'magnet', tags: ['attract', 'metal', 'physics'] },
  
  // Database specific
  { emoji: '🗄️', name: 'file cabinet', tags: ['database', 'storage', 'office'] },
  { emoji: '📦', name: 'package', tags: ['box', 'shipping', 'storage'] },
  { emoji: '📊', name: 'bar chart', tags: ['stats', 'data', 'analytics'] },
  { emoji: '📈', name: 'chart increasing', tags: ['growth', 'profit', 'increase'] },
  { emoji: '📉', name: 'chart decreasing', tags: ['loss', 'decrease', 'drop'] },
  { emoji: '📃', name: 'page with curl', tags: ['document', 'file', 'page'] },
  { emoji: '📄', name: 'page facing up', tags: ['document', 'file', 'page'] },
  { emoji: '📑', name: 'bookmark tabs', tags: ['document', 'tabs', 'organize'] },
  
  // Search & Find
  { emoji: '🔍', name: 'magnifying glass left', tags: ['search', 'find', 'look'] },
  { emoji: '🔎', name: 'magnifying glass right', tags: ['search', 'find', 'look'] },
  { emoji: '🔬', name: 'microscope', tags: ['science', 'lab', 'research'] },
  { emoji: '🔭', name: 'telescope', tags: ['space', 'look', 'stars'] },
  
  // Security
  { emoji: '🔒', name: 'locked', tags: ['secure', 'private', 'lock'] },
  { emoji: '🔓', name: 'unlocked', tags: ['open', 'public', 'unlock'] },
  { emoji: '🔐', name: 'locked with key', tags: ['secure', 'encrypted', 'private'] },
  { emoji: '🔑', name: 'key', tags: ['unlock', 'access', 'password'] },
  { emoji: '🗝️', name: 'old key', tags: ['key', 'unlock', 'vintage'] },
  { emoji: '🛡️', name: 'shield', tags: ['protect', 'security', 'defense'] },
  
  // Sync & Update
  { emoji: '🔄', name: 'counterclockwise arrows', tags: ['sync', 'refresh', 'update'] },
  { emoji: '⏪', name: 'fast reverse', tags: ['back', 'rewind', 'previous'] },
  { emoji: '⏩', name: 'fast forward', tags: ['next', 'forward', 'skip'] },
  { emoji: '⏫', name: 'double up arrow', tags: ['up', 'increase', 'fast'] },
  { emoji: '⏬', name: 'double down arrow', tags: ['down', 'decrease', 'fast'] },
  
  // Notification
  { emoji: '🔔', name: 'bell', tags: ['notification', 'alert', 'ring'] },
  { emoji: '🔕', name: 'bell with slash', tags: ['mute', 'silent', 'off'] },
  { emoji: '📢', name: 'loudspeaker', tags: ['announce', 'public', 'speaker'] },
  { emoji: '📣', name: 'megaphone', tags: ['announce', 'shout', 'speaker'] },
  { emoji: '📯', name: 'postal horn', tags: ['mail', 'post', 'horn'] },
  
  // Clock & Time
  { emoji: '🕐', name: 'one o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕑', name: 'two o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕒', name: 'three o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕓', name: 'four o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕔', name: 'five o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕕', name: 'six o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕖', name: 'seven o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕗', name: 'eight o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕘', name: 'nine o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕙', name: 'ten o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕚', name: 'eleven o clock', tags: ['time', 'clock', 'hour'] },
  { emoji: '🕛', name: 'twelve o clock', tags: ['time', 'clock', 'hour'] },
  
  // Database specific
  { emoji: '📊', name: 'bar chart', tags: ['data', 'statistics', 'analytics'] },
  { emoji: '📈', name: 'chart increasing', tags: ['data', 'growth', 'trend'] },
  { emoji: '📉', name: 'chart decreasing', tags: ['data', 'decline', 'trend'] },
  { emoji: '📋', name: 'clipboard', tags: ['data', 'list', 'copy'] },
  { emoji: '📝', name: 'memo', tags: ['note', 'write', 'document'] },
  { emoji: '📄', name: 'page facing up', tags: ['document', 'file', 'data'] },
  { emoji: '📃', name: 'page with curl', tags: ['document', 'file', 'data'] },
  { emoji: '📑', name: 'bookmark tabs', tags: ['document', 'bookmark', 'data'] },
  { emoji: '📂', name: 'open file folder', tags: ['folder', 'directory', 'data'] },
  { emoji: '📁', name: 'file folder', tags: ['folder', 'directory', 'data'] },
  
  // More tech
  { emoji: '🤖', name: 'robot face', tags: ['ai', 'automation', 'tech'] },
  { emoji: '💡', name: 'light bulb', tags: ['idea', 'inspiration', 'think'] },
  { emoji: '🔌', name: 'electric plug', tags: ['power', 'connect', 'charge'] },
  { emoji: '🔋', name: 'battery', tags: ['power', 'charge', 'energy'] },
  { emoji: '💸', name: 'money wings', tags: ['money', 'spend', 'cash'] },
  { emoji: '💰', name: 'money bag', tags: ['money', 'rich', 'cash'] },
  { emoji: '💳', name: 'credit card', tags: ['card', 'pay', 'money'] },
  { emoji: '💎', name: 'gem stone', tags: ['premium', 'diamond', 'valuable'] },
  // Animals & Nature
  { emoji: '🐶', name: 'dog face', tags: ['pet', 'puppy', 'animal'] },
  { emoji: '🐱', name: 'cat face', tags: ['pet', 'kitten', 'animal'] },
  { emoji: '🦊', name: 'fox face', tags: ['animal', 'sly', 'cunning'] },
  { emoji: '🐻', name: 'bear face', tags: ['animal', 'wild', 'strong'] },
  { emoji: '🐼', name: 'panda face', tags: ['animal', 'cute', 'china'] },
  { emoji: '🐨', name: 'koala', tags: ['animal', 'cute', 'australia'] },
  { emoji: '🐯', name: 'tiger face', tags: ['animal', 'wild', 'strong'] },
  { emoji: '🦁', name: 'lion face', tags: ['animal', 'king', 'wild'] },
  { emoji: '🐮', name: 'cow face', tags: ['animal', 'farm', 'moo'] },
  { emoji: '🐷', name: 'pig face', tags: ['animal', 'farm', 'oink'] },
  { emoji: '🐸', name: 'frog face', tags: ['animal', 'ribbit', 'amphibian'] },
  { emoji: '🐵', name: 'monkey face', tags: ['animal', 'ape', 'fun'] },
  { emoji: '🐔', name: 'chicken', tags: ['animal', 'bird', 'farm'] },
  { emoji: '🐧', name: 'penguin', tags: ['animal', 'bird', 'cold'] },
  { emoji: '🐦', name: 'bird', tags: ['animal', 'fly', 'tweet'] },
  { emoji: '🐤', name: 'baby chick', tags: ['animal', 'cute', 'bird'] },
  { emoji: '🦄', name: 'unicorn face', tags: ['magic', 'fantasy', 'rainbow'] },
  { emoji: '🐝', name: 'honeybee', tags: ['insect', 'honey', 'buzz'] },
  { emoji: '🐛', name: 'bug', tags: ['insect', 'caterpillar', 'cute'] },
  { emoji: '🦋', name: 'butterfly', tags: ['insect', 'beautiful', 'wings'] },
  { emoji: '🐞', name: 'lady beetle', tags: ['insect', 'ladybug', 'luck'] },
  { emoji: '🐙', name: 'octopus', tags: ['sea', 'animal', 'tentacles'] },
  { emoji: '🐠', name: 'tropical fish', tags: ['fish', 'sea', 'colorful'] },
  { emoji: '🐳', name: 'spouting whale', tags: ['sea', 'big', 'ocean'] },
  { emoji: '🐬', name: 'dolphin', tags: ['sea', 'smart', 'ocean'] },
  { emoji: '🦈', name: 'shark', tags: ['sea', 'danger', 'predator'] },

  // Flags
  { emoji: '🏳️', name: 'white flag', tags: ['surrender', 'truce', 'peace'] },
  { emoji: '🏴', name: 'black flag', tags: ['pirate', 'dark', 'anarchy'] },
  { emoji: '🇺🇸', name: 'United States', tags: ['usa', 'america', 'stars'] },
  { emoji: '🇬🇧', name: 'United Kingdom', tags: ['uk', 'britain', 'union jack'] },
  { emoji: '🇫🇷', name: 'France', tags: ['france', 'paris', 'europe'] },
  { emoji: '🇩🇪', name: 'Germany', tags: ['germany', 'berlin', 'europe'] },
  { emoji: '🇯🇵', name: 'Japan', tags: ['japan', 'tokyo', 'asia'] },
  { emoji: '🇨🇳', name: 'China', tags: ['china', 'asia', 'beijing'] },
  { emoji: '🇮🇳', name: 'India', tags: ['india', 'asia', 'delhi'] },
  { emoji: '🇧🇷', name: 'Brazil', tags: ['brazil', 'south america', 'rio'] },
  { emoji: '🇨🇦', name: 'Canada', tags: ['canada', 'north america', 'maple'] },
  { emoji: '🇦🇺', name: 'Australia', tags: ['australia', 'oceania', 'sydney'] },
  { emoji: '🇪🇸', name: 'Spain', tags: ['spain', 'europe', 'madrid'] },
  { emoji: '🇮🇹', name: 'Italy', tags: ['italy', 'europe', 'rome'] },
  { emoji: '🇰🇷', name: 'South Korea', tags: ['korea', 'asia', 'seoul'] },
  { emoji: '🇷🇺', name: 'Russia', tags: ['russia', 'europe', 'moscow'] },
  { emoji: '🇲🇽', name: 'Mexico', tags: ['mexico', 'north america', 'cancun'] },
  { emoji: '🇳🇱', name: 'Netherlands', tags: ['netherlands', 'europe', 'amsterdam'] },
];